"""Episode registry: status lifecycle, list view, and sync to the 'Episodes' tab of the Google Sheet
(the LinkedInPost /videos page reads that tab)."""
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

from adapters.common import ROOT, env, google_service_info

STATUSES = ["idea", "scripted", "approved", "rendered", "reviewed", "scheduled", "posted"]
COLS = ["id", "title", "series", "topic_area", "format", "status", "sponsor", "video_url", "cover_url",
        "carousel_urls_json", "youtube_url", "instagram_url", "posted_at", "updated_at", "notes"]
TAB = "Episodes"


def now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def episode_dirs() -> list:
    return sorted(p.parent for p in (ROOT / "episodes").glob("*/episode.json"))


def resolve(ref: str) -> Path:
    p = Path(ref)
    if (p / "episode.json").exists():
        return p
    q = ROOT / "episodes" / ref
    if (q / "episode.json").exists():
        return q
    raise SystemExit(f"episode not found: {ref}")


def read(ep_dir: Path) -> dict:
    return json.loads((ep_dir / "episode.json").read_text())


def write(ep_dir: Path, ep: dict) -> None:
    ep["updated_at"] = now()
    (ep_dir / "episode.json").write_text(json.dumps(ep, indent=2, ensure_ascii=False) + "\n")


def status_of(ep: dict) -> str:
    return ep.get("status") or "approved"  # legacy episodes (pre-registry) count as approved


def sha256(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def set_status(ep_dir: Path, status: str, skip_verify: bool = False) -> None:
    if status not in STATUSES:
        raise SystemExit(f"status must be one of {STATUSES}")
    ep = read(ep_dir)
    if status == "approved":  # QA gate (verify.py): audience-declared scripts must pass the verifier agents first
        import verify
        ok, why = verify.is_clear(ep)
        if not ok and not skip_verify:
            raise SystemExit(f"cannot approve {ep['id']}: {why}  (override: --skip-verify)")
        if not ok:
            print(f"WARNING: approving without a passing QA report ({why})")
    ep["status"] = status
    if status == "reviewed":  # provenance: lock the exact file the owner reviewed
        video = ROOT / "out" / ep["id"] / "final.mp4"
        if not video.exists():
            raise SystemExit(f"cannot mark reviewed: {video} does not exist")
        ep["reviewed_sha256"] = sha256(video)
    write(ep_dir, ep)


def advance(ep_dir: Path, status: str) -> None:
    """Move status forward only (never backward)."""
    ep = read(ep_dir)
    if STATUSES.index(status) > STATUSES.index(status_of(ep)):
        ep["status"] = status
        write(ep_dir, ep)


def add_post(ep_dir: Path, platform: str, url: str, visibility: str, file_sha256: str = "") -> None:
    ep = read(ep_dir)
    ep.setdefault("posts", []).append({"platform": platform, "url": url, "visibility": visibility, "posted_at": now(),
                                       "sha256": file_sha256})
    if visibility == "public":
        ep["status"] = "posted"
    write(ep_dir, ep)


def row(ep_dir: Path, ep: dict) -> list:
    out = ROOT / "out" / ep["id"]
    posts = {p["platform"]: p["url"] for p in ep.get("posts", [])}
    carousel = sorted(str(p.relative_to(ROOT)) for p in (out / "carousel").glob("slide*.png")) if (out / "carousel").exists() else []
    video = ep.get("files", {}).get("video_url") or (f"out/{ep['id']}/final.mp4" if (out / "final.mp4").exists() else "")
    sponsor = ep.get("sponsor") or ""
    if isinstance(sponsor, dict):
        sponsor = sponsor.get("brand", "")
    posted_at = max((p.get("posted_at", "") for p in ep.get("posts", [])), default="")
    return [ep["id"], ep.get("title", ""), ep.get("series", ""), ep.get("topic_area", ""), (ep.get("format_id") or ep.get("content_format") or ""),
            status_of(ep), sponsor, video, ep.get("files", {}).get("cover_url", ""), json.dumps(carousel),
            posts.get("youtube", ""), posts.get("instagram", ""), posted_at, ep.get("updated_at", ""), ep.get("notes", "")]


def table() -> str:
    lines = [f"{'id':34} {'status':10} {'format':14} {'series':26} posts"]
    for d in episode_dirs():
        ep = read(d)
        posts = ",".join(f"{p['platform']}:{p.get('visibility','')}" for p in ep.get("posts", [])) or "-"
        lines.append(f"{ep['id']:34} {status_of(ep):10} {(ep.get('format_id') or ep.get('content_format') or '-'):14} {ep.get('series','-')[:26]:26} {posts}")
    return "\n".join(lines)


def write_markdown() -> None:
    lines = ["# Episodes (generated by `python run.py list`; do not edit)", "",
             "| id | title | status | format | series | posts |", "|---|---|---|---|---|---|"]
    for d in episode_dirs():
        ep = read(d)
        posts = ", ".join(f"[{p['platform']}]({p['url']})" if p.get("url") else p["platform"] for p in ep.get("posts", [])) or "-"
        lines.append(f"| {ep['id']} | {ep.get('title','')} | {status_of(ep)} | {(ep.get('format_id') or ep.get('content_format') or '-')} | {ep.get('series','-')} | {posts} |")
    (ROOT / "EPISODES.md").write_text("\n".join(lines) + "\n")


def _sheets():
    from google.oauth2 import service_account
    from googleapiclient.discovery import build
    creds = service_account.Credentials.from_service_account_info(
        google_service_info(), scopes=["https://www.googleapis.com/auth/spreadsheets"])
    return build("sheets", "v4", credentials=creds, cache_discovery=False).spreadsheets()


def sync() -> str:
    sid = env("GOOGLE_SHEET_ID")
    sh = _sheets()
    tabs = [s["properties"]["title"] for s in sh.get(spreadsheetId=sid, fields="sheets.properties.title").execute()["sheets"]]
    if TAB not in tabs:
        sh.batchUpdate(spreadsheetId=sid, body={"requests": [{"addSheet": {"properties": {"title": TAB, "gridProperties": {"frozenRowCount": 1}}}}]}).execute()
    existing = sh.values().get(spreadsheetId=sid, range=f"{TAB}!A:A").execute().get("values", [])
    ids = {r[0]: i + 1 for i, r in enumerate(existing) if r}
    data = [{"range": f"{TAB}!A1", "values": [COLS]}]
    next_row = len(existing) + 1 if existing else 2
    for d in episode_dirs():
        ep = read(d)
        r = ids.get(ep["id"])
        if r is None:
            r, next_row = next_row, next_row + 1
        data.append({"range": f"{TAB}!A{r}", "values": [row(d, ep)]})
    sh.values().batchUpdate(spreadsheetId=sid, body={"valueInputOption": "RAW", "data": data}).execute()
    write_markdown()
    return f"synced {len(data) - 1} episode(s) to tab '{TAB}'"
