#!/usr/bin/env python3
"""Emit build-time feature flags from features.yaml into worker and frontend."""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError as exc:
    print('PyYAML is required: pip install -r requirements.txt', file=sys.stderr)
    raise SystemExit(1) from exc

ROOT = Path(__file__).resolve().parent.parent
FEATURES_FILE = ROOT / 'features.yaml'

TS_HEADER = """// AUTO-GENERATED by scripts/generate_features.py — do not edit.
// Source: features.yaml

"""

DEFAULTS: dict[str, bool | str] = {
    'deploymentMode': 'saas',
    'newsResearch': True,
    'campaign': True,
    'multiProviderLlm': False,
    'contentReview': False,
    'contentFlow': False,
    'enrichment': True,
}

# TypeScript export name per YAML key (extend when adding features)
TS_CONST_NAMES: dict[str, str] = {
    'newsResearch': 'FEATURE_NEWS_RESEARCH',
    'campaign': 'FEATURE_CAMPAIGN',
    'multiProviderLlm': 'FEATURE_MULTI_PROVIDER_LLM',
    'contentReview': 'FEATURE_CONTENT_REVIEW',
    'contentFlow': 'FEATURE_CONTENT_FLOW',
    'enrichment': 'FEATURE_ENRICHMENT',
}


def load_feature_map() -> dict[str, bool | str]:
    if not FEATURES_FILE.is_file():
        return dict(DEFAULTS)
    raw = yaml.safe_load(FEATURES_FILE.read_text()) or {}
    if not isinstance(raw, dict):
        return dict(DEFAULTS)
    out: dict[str, bool | str] = {}
    for key, default in DEFAULTS.items():
        if key not in raw:
            out[key] = default
            continue
        val = raw[key]
        if isinstance(default, str):
            out[key] = str(val) if isinstance(val, str) else default
        else:
            out[key] = bool(val) if isinstance(val, bool) else default
    return out


def emit_ts(features: dict[str, bool | str]) -> str:
    lines = [TS_HEADER]
    for key in sorted(features.keys()):
        value = features[key]
        if isinstance(value, str):
            if key == 'deploymentMode':
                lines.append(f"export const deploymentMode = '{value}' as const;\n")
                lines.append(f"export type DeploymentMode = typeof deploymentMode;\n")
            else:
                lines.append(f"export const {key} = '{value}' as const;\n")
        else:
            const = TS_CONST_NAMES.get(key, f'FEATURE_{key.upper()}')
            lines.append(f'export const {const} = {"true" if value else "false"} as const;\n')
    return ''.join(lines)


def update_wrangler_deployment_mode(mode: str) -> None:
    """Keep DEPLOYMENT_MODE in worker/wrangler.jsonc in sync with features.yaml."""
    import re
    wrangler = ROOT / 'worker' / 'wrangler.jsonc'
    if not wrangler.is_file():
        return
    text = wrangler.read_text()
    updated = re.sub(r'"DEPLOYMENT_MODE"\s*:\s*"[^"]*"', f'"DEPLOYMENT_MODE": "{mode}"', text)
    if updated != text:
        wrangler.write_text(updated)
        print(f'Updated DEPLOYMENT_MODE={mode} in worker/wrangler.jsonc')


def main() -> None:
    features = load_feature_map()
    body = emit_ts(features)
    for rel in ('worker/src/generated/features.ts', 'frontend/src/generated/features.ts'):
        path = ROOT / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body)
        print(f'Wrote {path.relative_to(ROOT)}')
    update_wrangler_deployment_mode(str(features.get('deploymentMode', 'saas')))


if __name__ == '__main__':
    main()
