#!/usr/bin/env python3
"""Emit build-time feature flags from features.yaml into worker and frontend."""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError as exc:
    print('PyYAML is required: pip install -r requirements.txt', file=sys.stderr)
    raise SystemExit(1) from exc

ROOT = Path(__file__).resolve().parent.parent
FEATURES_FILE = ROOT / 'features.yaml'

TS_HEADER = """// AUTO-GENERATED by scripts/generate_features.py — do not edit.
// Source: features.yaml

"""

DEFAULTS: dict[str, bool] = {
    'newsResearch': True,
}

# TypeScript export name per YAML key (extend when adding features)
TS_CONST_NAMES: dict[str, str] = {
    'newsResearch': 'FEATURE_NEWS_RESEARCH',
}


def load_feature_map() -> dict[str, bool]:
    if not FEATURES_FILE.is_file():
        return dict(DEFAULTS)
    raw = yaml.safe_load(FEATURES_FILE.read_text()) or {}
    if not isinstance(raw, dict):
        return dict(DEFAULTS)
    out: dict[str, bool] = {}
    for key, default in DEFAULTS.items():
        if key not in raw:
            out[key] = default
            continue
        val = raw[key]
        out[key] = bool(val) if isinstance(val, bool) else default
    return out


def emit_ts(features: dict[str, bool]) -> str:
    lines = [TS_HEADER]
    for key in sorted(features.keys()):
        const = TS_CONST_NAMES.get(key, f'FEATURE_{key.upper()}')
        enabled = features[key]
        lines.append(f'export const {const} = {"true" if enabled else "false"} as const;\n')
    return ''.join(lines)


def main() -> None:
    features = load_feature_map()
    body = emit_ts(features)
    for rel in ('worker/src/generated/features.ts', 'frontend/src/generated/features.ts'):
        path = ROOT / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body)
        print(f'Wrote {path.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
