#!/usr/bin/env python3
"""Generate remotion-app/src/tokens.ts from direction/tokens.yaml.
Run: python scripts/gen_tokens_ts.py
The generated file is checked into git so the Remotion build is self-contained.
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

_ROOT = Path(__file__).resolve().parent.parent
_SRC = _ROOT / "direction" / "tokens.yaml"
_DEST = _ROOT / "remotion-app" / "src" / "tokens.ts"


def _val(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, str):
        return f'"{v}"'
    if isinstance(v, list):
        return "[" + ", ".join(_val(x) for x in v) + "]"
    if isinstance(v, dict):
        items = ", ".join(f"{k}: {_val(vv)}" for k, vv in v.items())
        return "{" + items + "}"
    return f'"{v}"'


def _section(name: str, data: dict, indent: int = 0) -> list[str]:
    pad = "  " * indent
    lines = [f"{pad}{name}: {{"]
    for k, v in data.items():
        if isinstance(v, dict):
            lines += _section(k, v, indent + 1)
        else:
            lines.append(f"{'  ' * (indent + 1)}{k}: {_val(v)},")
    lines.append(f"{pad}}},")
    return lines


def generate() -> str:
    tok = yaml.safe_load(_SRC.read_text())
    lines = [
        "// AUTO-GENERATED by scripts/gen_tokens_ts.py — DO NOT EDIT DIRECTLY.",
        "// Edit direction/tokens.yaml and re-run the script.",
        "",
        "export const tokens = {",
    ]
    for section_name, section_data in tok.items():
        if isinstance(section_data, dict):
            lines += _section(section_name, section_data, indent=1)
        elif isinstance(section_data, list):
            # banned_defaults etc — emit as array
            lines.append(f"  {section_name}: {_val(section_data)},")
        else:
            lines.append(f"  {section_name}: {_val(section_data)},")
    lines += ["} as const;", "", "export type Tokens = typeof tokens;", ""]
    return "\n".join(lines)


def main() -> int:
    ts = generate()
    _DEST.write_text(ts)
    print(f"Written {_DEST.relative_to(_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
